DROP TABLE IF EXISTS TODO_TBL;
CREATE TABLE TODO_TBL (
id INT AUTO_INCREMENT  PRIMARY KEY,
done boolean NOT NULL,
task VARCHAR(50) NOT NULL,
lastUpdateTime VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS USER_TBL;
CREATE TABLE USER_TBL (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL
);